### ISSUE TITLE
接口方法名notify识别不出来

### ISSUE THREAD

**Issue by yiguanke** [easyyapi/easyyapi.github.io#3]
接口方法名notify识别不出来，全小写notify

**Comment by tangcent** [comment]
是的，为了减少解析耗时，目前过滤掉了Object里的一些方法名。
https://github.com/Earth-1610/intellij-kotlin/blob/2af02a23436792ec78dea8b147a7f26fa554b37c/intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardJvmClassHelper.kt#L430-L441

暂时没有好的方法可以在不更新插件的情况下突破这个限制。

**Comment by tangcent** [comment]
在 http://tangcent/easy-yapi#928 中处理
